### ISSUE TITLE
AWS SDK crashes on publish

### ISSUE THREAD

**Issue by startupthekid** [guidomb/carthage_cache#38]
When I run `carthage_cache publish`, I get the following output:

```
error: . Use --trace to view backtrace
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-resources-2.9.17/lib/aws-sdk-resources/resource.rb:134:in `rescue in exists?': Aws::S3::Errors::Http301Error
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-resources-2.9.17/lib/aws-sdk-resources/resource.rb:131:in `exists?'
	from /Library/Ruby/Gems/2.0.0/gems/carthage_cache-0.8.3/lib/carthage_cache/repository.rb:16:in `archive_exist?'
	from /Library/Ruby/Gems/2.0.0/gems/carthage_cache-0.8.3/lib/carthage_cache/application.rb:25:in `archive_exist?'
	from /Library/Ruby/Gems/2.0.0/gems/carthage_cache-0.8.3/lib/carthage_cache/application.rb:43:in `create_archive'
	from /Library/Ruby/Gems/2.0.0/gems/carthage_cache-0.8.3/exe/carthage_cache:73:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'
```

Interestingly, when I change the bucket name to one that doesn't match what I have on S3, carthage_cache archives everything but fails to find the bucket.

**Comment by samuelbeek** [comment]
Do you have some AWS environment variables set in your bash_profile? Do you use AWS for other projects as well. That's what's causing the issue on my computer.

**Comment by guidomb** [comment]
Have you run `carthage_cache config` to generate `.carthage_cache.yml` with the proper amazon configuration?. https://github.com/guidomb/carthage_cache#setup
