### ISSUE TITLE
Error: Use RbConfig instead of obsolete and deprecated Config.

### ISSUE THREAD

**Issue by msanders** [guidomb/carthage_cache#9]
I'm getting this error on Travis for the Xcode 7.2 image:

```
carthage_cache install --bucket-name [BUCKET]
/Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.7/lib/commander/user_interaction.rb:333:in `const_get': Use RbConfig instead of obsolete and deprecated Config.
error: . Use --trace to view backtrace
```

Bummed since this would speed up our builds a lot.

**Comment by guidomb** [comment]
Could you pass `--trace` so I can see the full stack tracer. Also have you [configured](https://github.com/guidomb/carthage_cache#setup) the AWS credentials either using the environmental variables or `.carthage-cache.yml` ?

**Comment by msanders** [comment]
Yes, environment variables are being set correctly (not using the config file). Here is the trace:

```
bundle exec carthage_cache install --bucket-name [BUCKET] --trace
/Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.7/lib/commander/user_interaction.rb:333:in `const_get': Use RbConfig instead of obsolete and deprecated Config.
/Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/aws-sdk-resources-2.2.14/lib/aws-sdk-resources/resource.rb:134:in `rescue in exists?': Aws::S3::Errors::Forbidden
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/aws-sdk-resources-2.2.14/lib/aws-sdk-resources/resource.rb:131:in `exists?'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/carthage_cache-0.2.1/lib/carthage_cache/repository.rb:16:in `archive_exist?'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/carthage_cache-0.2.1/lib/carthage_cache.rb:35:in `archive_exist?'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/carthage_cache-0.2.1/lib/carthage_cache.rb:39:in `install_archive'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/carthage_cache-0.2.1/exe/carthage_cache:48:in `block (2 levels) in <top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.7/lib/commander/command.rb:178:in `call'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.7/lib/commander/command.rb:178:in `call'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.7/lib/commander/command.rb:153:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.7/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.7/lib/commander/runner.rb:68:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.7/lib/commander/delegates.rb:15:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.7/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by guidomb** [comment]
Judging by the stack trace the AWS credentials you are using don't have access to the bucket. To check my theory use the same access key locally and see if it works.

Better error reporting is something that is needed for the gem.

**Comment by guidomb** [comment]
Where you able to double check your AWS credentials? Are you still having this issue?

**Comment by msanders** [comment]
That fixed it, although I still get this warning:

```
+bundle exec carthage_cache install --bucket-name [BUCKET NAME]
/Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.7/lib/commander/user_interaction.rb:333:in `const_get': Use RbConfig instead of obsolete and deprecated Config.
```

Feel free to close this if that's expected. Thanks!

**Comment by guidomb** [comment]
Is not expected but I guess it only happens with some ruby version. I don't see that error but I am using a newer version.

**Comment by guidomb** [comment]
I've just released a new version that updates all dependencies. I updates commander to the latest version which should fix that warning https://github.com/commander-rb/commander/issues/24

**Comment by msanders** [comment]
Great. Thanks for this, looks like it will help our build times a lot.

**Comment by guidomb** [comment]
Cool! Let me know if you any other problem.
